# Generated by Django 5.1.3 on 2024-12-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_category_subcategory_post_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
